service: test
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'local'}
  region: us-east-1

functions:
  api:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules

plugins:
  - serverless-webpack
  - serverless-offline